{{- if and (not .Values.database.existingSecret) .Values.database.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smarthome-metrics.secretName" . }}
  labels:
    {{- include "smarthome-metrics.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.database.password | quote }}
{{- end }}
